In [7]:
%run testProject3.py

训练数据和测试数据: (50000, 32, 32, 3) (50000,) (10000, 32, 32, 3) (10000,)
标签的种类:  [0 1 2 3 4 5 6 7 8 9]


In [8]:
for i in range(5):
    k=1
    
    

In [9]:
k

1

In [10]:
y_train[:10]

array([6, 9, 9, 4, 1, 1, 2, 7, 8, 3])

In [11]:
import random

In [13]:
type(y_train)

numpy.ndarray

In [14]:
sample_list = [i for i in range(len(y_train))]

In [15]:
len(sample_list)

50000

In [16]:
sample_list=random.sample(sample_list,10)

In [17]:
sample_list

[39050, 26684, 17501, 20573, 19982, 47349, 41253, 47459, 35327, 12856]

In [18]:
y_train[sample_list]

array([9, 0, 5, 4, 0, 1, 8, 7, 0, 1])

In [19]:
X_train[:10]

array([[[[ 59.,  62.,  63.],
         [ 43.,  46.,  45.],
         [ 50.,  48.,  43.],
         ...,
         [158., 132., 108.],
         [152., 125., 102.],
         [148., 124., 103.]],

        [[ 16.,  20.,  20.],
         [  0.,   0.,   0.],
         [ 18.,   8.,   0.],
         ...,
         [123.,  88.,  55.],
         [119.,  83.,  50.],
         [122.,  87.,  57.]],

        [[ 25.,  24.,  21.],
         [ 16.,   7.,   0.],
         [ 49.,  27.,   8.],
         ...,
         [118.,  84.,  50.],
         [120.,  84.,  50.],
         [109.,  73.,  42.]],

        ...,

        [[208., 170.,  96.],
         [201., 153.,  34.],
         [198., 161.,  26.],
         ...,
         [160., 133.,  70.],
         [ 56.,  31.,   7.],
         [ 53.,  34.,  20.]],

        [[180., 139.,  96.],
         [173., 123.,  42.],
         [186., 144.,  30.],
         ...,
         [184., 148.,  94.],
         [ 97.,  62.,  34.],
         [ 83.,  53.,  34.]],

        [[177., 144., 116.],
       

In [20]:
X_train[:1]

array([[[[ 59.,  62.,  63.],
         [ 43.,  46.,  45.],
         [ 50.,  48.,  43.],
         ...,
         [158., 132., 108.],
         [152., 125., 102.],
         [148., 124., 103.]],

        [[ 16.,  20.,  20.],
         [  0.,   0.,   0.],
         [ 18.,   8.,   0.],
         ...,
         [123.,  88.,  55.],
         [119.,  83.,  50.],
         [122.,  87.,  57.]],

        [[ 25.,  24.,  21.],
         [ 16.,   7.,   0.],
         [ 49.,  27.,   8.],
         ...,
         [118.,  84.,  50.],
         [120.,  84.,  50.],
         [109.,  73.,  42.]],

        ...,

        [[208., 170.,  96.],
         [201., 153.,  34.],
         [198., 161.,  26.],
         ...,
         [160., 133.,  70.],
         [ 56.,  31.,   7.],
         [ 53.,  34.,  20.]],

        [[180., 139.,  96.],
         [173., 123.,  42.],
         [186., 144.,  30.],
         ...,
         [184., 148.,  94.],
         [ 97.,  62.,  34.],
         [ 83.,  53.,  34.]],

        [[177., 144., 116.],
       

In [21]:
X_train[:1,:1]

array([[[[ 59.,  62.,  63.],
         [ 43.,  46.,  45.],
         [ 50.,  48.,  43.],
         [ 68.,  54.,  42.],
         [ 98.,  73.,  52.],
         [119.,  91.,  63.],
         [139., 107.,  75.],
         [145., 110.,  80.],
         [149., 117.,  89.],
         [149., 120.,  93.],
         [131., 103.,  77.],
         [125.,  99.,  76.],
         [142., 115.,  91.],
         [144., 112.,  86.],
         [137., 105.,  79.],
         [129.,  97.,  71.],
         [137., 106.,  79.],
         [134., 106.,  76.],
         [124.,  97.,  64.],
         [139., 113.,  78.],
         [139., 112.,  75.],
         [133., 105.,  69.],
         [136., 105.,  74.],
         [139., 108.,  77.],
         [152., 120.,  89.],
         [163., 131., 100.],
         [168., 136., 108.],
         [159., 129., 102.],
         [158., 130., 104.],
         [158., 132., 108.],
         [152., 125., 102.],
         [148., 124., 103.]]]])